# Generated by Django 5.2.8 on 2025-11-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='imagen',
            new_name='foto',
        ),
    ]
